### ISSUE TITLE
How to validate the token?

### ISSUE THREAD

**Issue by pattnaik-soumitri** [ruigomeseu/vue-turnstile#13]
Given that we have a handle to the `token`, how do we verify if it is valid?

Is there a built-in method?

**Comment by ruigomeseu** [comment]
You would send the token to your backend and validate it there:
https://developers.cloudflare.com/turnstile/get-started/server-side-validation/

**Comment by pattnaik-soumitri** [comment]
@ruigomeseu  thanks.

Thanks for the contribution.
