### ISSUE TITLE
Turnstile instance not removed before unmount

### ISSUE THREAD

**Issue by KyleRicardo** [ruigomeseu/vue-turnstile#4]
Hi, thanks for your awesome lib that help me easily integrate turnstile into my project.

However I encountered a problem: When I navigate to another page, the console begin to print this repeatedly:

> [Cloudflare Turnstile] Cannot find Widget cf-chl-widget-ssgkn, consider using turnstile.remove() to clean up a widget..

I wonder how to call `remove()` before unmount. 

Or did I use it wrong? Need your help, thanks!

**Comment by ruigomeseu** [comment]
Fixed in 1.0.4
